" __   _(_)_ __ ___  _ __ ___  "
" \ \ / / | '_ ` _ \| '__/ __| "
"  \ V /| | | | | | | | | (__  "
" (_)_/ |_|_| |_| |_|_|  \___| "
"
" === pre init ===
scriptencoding utf-8
" syntax off
" filetype indent plugin off
syntax enable
filetype plugin indent on

let $MYVIMRC = expand('<sfile>')

if exists('$SHELL')
  set shell=$SHELL
endif

if fnamemodify(&shell, ':t:r') == 'nyagos'
  set shellcmdflag=-c
endif

set encoding=utf-8
set fileencodings=utf-8,sjis

if empty("$XDG_CACHE_HOME")
  let $XDG_CACHE_HOME="$HOME/.cache"
endif

if empty("$XDG_CONFIG_HOME")
  let $XDG_CONFIG_HOME="$HOME/.config"
endif

if empty("$XDG_DATA_HOME")
  let $XDG_DATA_HOME="$HOME/.local/share"
endif

set backup
set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let &packpath = &runtimepath

" === configures ===
" --- backup ---
set backup
let s:backup_dirpath = expand('$XDG_CACHE_HOME/vim/backup')
call mkdir(s:backup_dirpath, 'p')
execute 'set backupdir=' .. s:backup_dirpath

" --- swapfile ---
set swapfile
let s:swap_dirpath = expand('$XDG_CACHE_HOME/vim/swap')
call mkdir(s:swap_dirpath, 'p')
execute 'set directory=' .. s:swap_dirpath

" --- undo ---
if has('persistent_undo')
  set undofile
  let s:undo_dirpath = expand('$XDG_CACHE_HOME/vim/undo')
  call mkdir(s:undo_dirpath, 'p')
  execute 'set undodir=' .. s:undo_dirpath
endif


set helplang=ja,en

set clipboard=

set title

set virtualedit=onemore

set hidden
set number
set cursorline

set showmatch
set showcmd

set whichwrap=b,s,<,>,[,]

set scrolloff=2

set modeline
set modelines=3

set keywordprg=:help

set mouse=a

set backspace=indent,eol,start
" === indentation ===
set noexpandtab " et == use space
set smarttab
set tabstop=4
set shiftwidth=0 softtabstop=-1 " follow to tabstop
set autoindent
set smartindent

" === slash searching ===
set incsearch
set ignorecase
set smartcase
set hlsearch

" === wildmenu ===
set wildmenu
set wildmode=list:longest,full
if has('patch-8.2.4325')
  set wildmode=full
  set wildoptions=pum
endif

" === others ===
" set completefunc=
set completeopt=menuone,popup
" inoremap <expr> <Tab>  pumvisible() ? "<C-n>" : "<C-x><C-o>"
" inoremap <expr> <S-Tab>  pumvisible() ? "<C-p>" : "<C-v><Tab>"
inoremap <expr> <CR> pumvisible() ? "<C-y>" : "<CR>"
" imap <expr> <Tab> pumvisible() ? "<C-y>" : "<Plug>(complete)"
" inoremap <Plug>(complete)f <C-x><C-f>
" inoremap <Plug>(complete)p <C-x><C-p>
" inoremap <Plug>(complete)o <C-x><C-o>

" === load rcs ===
runtime! rc/*.vim

" === post init ===
" syntax enable
" filetype plugin indent on

" --- colorscheme ---
if has('termguicolors')
  if $TERM != 'Linux'
    set termguicolors
  endif
endif
set background=dark
try
  colorscheme iceberg
  " colorscheme molokai
  " colorscheme tokyonight
  " colorscheme catppuccin_mocha
  " colorscheme github_dark
catch
  try
    colorscheme retrobox
  catch
    colorscheme darkblue
  endtry
endtry

" === after ===
" _vim: set et ts=2 sw=0 sts=-1 fmr={{{,}}}:
